In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [8]:
sent=[ 'the glass of milk',
      'the glass of juice',
      'the cup of tea',
      'I am a good boy',
      'I am a good developer',
      'understand the meaning of words',
      'your videos are good',]

In [9]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [11]:
#define the vocabulary size
voc_size=10000

In [13]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [12]:
#one hot representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr


[[4796, 1168, 1309, 3363],
 [4796, 1168, 1309, 571],
 [4796, 4156, 1309, 6883],
 [6168, 484, 2453, 9168, 8026],
 [6168, 484, 2453, 9168, 3849],
 [2416, 4796, 7574, 1309, 8956],
 [8899, 5139, 6243, 9168]]

In [16]:
#word embedding representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential



In [17]:
import numpy as np

In [20]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length) #zeroes in beginning and you can also write post #to convert all the sentences into same length means all the sentences will be of equal words
print(embedded_docs)

[[   0    0    0    0 4796 1168 1309 3363]
 [   0    0    0    0 4796 1168 1309  571]
 [   0    0    0    0 4796 4156 1309 6883]
 [   0    0    0 6168  484 2453 9168 8026]
 [   0    0    0 6168  484 2453 9168 3849]
 [   0    0    0 2416 4796 7574 1309 8956]
 [   0    0    0    0 8899 5139 6243 9168]]


In [ ]:
#feature representation
dim=10 #dimension is 10

In [23]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')


c:\Users\manasi kulkarni\anaconda3\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [24]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [25]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 602ms/step


array([[[-0.01488987, -0.02567079,  0.0038102 , -0.01529875,
         -0.03460998,  0.03978616,  0.00198948,  0.0443767 ,
          0.04709062,  0.02880717],
        [-0.01488987, -0.02567079,  0.0038102 , -0.01529875,
         -0.03460998,  0.03978616,  0.00198948,  0.0443767 ,
          0.04709062,  0.02880717],
        [-0.01488987, -0.02567079,  0.0038102 , -0.01529875,
         -0.03460998,  0.03978616,  0.00198948,  0.0443767 ,
          0.04709062,  0.02880717],
        [-0.01488987, -0.02567079,  0.0038102 , -0.01529875,
         -0.03460998,  0.03978616,  0.00198948,  0.0443767 ,
          0.04709062,  0.02880717],
        [-0.02157623, -0.03521515, -0.03785676, -0.00503451,
         -0.027415  ,  0.00951042,  0.01383169,  0.03932858,
         -0.04461458,  0.01763853],
        [-0.01572223, -0.01178414, -0.01649293, -0.04442041,
         -0.02127093,  0.01114513, -0.0126393 , -0.01590697,
          0.0375989 ,  0.01742684],
        [-0.02941271, -0.00381977, -0.02500147, -0.0

In [26]:
embedded_docs[0]

array([   0,    0,    0,    0, 4796, 1168, 1309, 3363])

In [35]:
import numpy as np
model.predict(np.array([embedded_docs[0]]))



1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step


array([[[-0.01488987, -0.02567079,  0.0038102 , -0.01529875,
         -0.03460998,  0.03978616,  0.00198948,  0.0443767 ,
          0.04709062,  0.02880717],
        [-0.01488987, -0.02567079,  0.0038102 , -0.01529875,
         -0.03460998,  0.03978616,  0.00198948,  0.0443767 ,
          0.04709062,  0.02880717],
        [-0.01488987, -0.02567079,  0.0038102 , -0.01529875,
         -0.03460998,  0.03978616,  0.00198948,  0.0443767 ,
          0.04709062,  0.02880717],
        [-0.01488987, -0.02567079,  0.0038102 , -0.01529875,
         -0.03460998,  0.03978616,  0.00198948,  0.0443767 ,
          0.04709062,  0.02880717],
        [-0.02157623, -0.03521515, -0.03785676, -0.00503451,
         -0.027415  ,  0.00951042,  0.01383169,  0.03932858,
         -0.04461458,  0.01763853],
        [-0.01572223, -0.01178414, -0.01649293, -0.04442041,
         -0.02127093,  0.01114513, -0.0126393 , -0.01590697,
          0.0375989 ,  0.01742684],
        [-0.02941271, -0.00381977, -0.02500147, -0.0